package au.com.unohomeloans.challenge.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "DatesCalculatorHistory")
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DateCalculationItem {

    private String id;
    private String startDate;
    private String endDate;
    private int result;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getStartDate() {
        return startDate;
    }

    @DynamoDBAttribute
    public String getEndDate() {
        return endDate;
    }

    @DynamoDBAttribute
    public int getResult() {
        return result;
    }

}